### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by dustinfarris** [toranb/elixir-gleam-match#1]
Hi Toran!

FYI I had trouble compiling this:

```
error: Syntax error
   ┌─ /Users/dustin/learn/elixir-gleam-match/deps/gleam_stdlib/src/gleam/bit_string.gleam:60:5
   │
60 │     <<>> -> True
   │     ^ Unexpected token

Expected one of "->", "[", "[]", "if", "tuple", "|", r#"\"(([^\\\\\"]|\\\\.)*)\""#, r#"-?[0-9]+\\.[0-9]*"#, r#"-[0-9]+"#, r#"[0-9]+"#, r#"[A-Z][0-9A-Za-z]*"#, r#"[a-z][0-9a-z_]*"#, r#"_[A-Za-z_]*"#
** (exit) 1
    lib/mix/tasks/compiler/gleam.ex:7: Mix.Tasks.Compile.Gleam.run/1
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/tasks/compile.all.ex:76: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.10.4) lib/mix/tasks/compile.all.ex:56: Mix.Tasks.Compile.All.do_compile/4
    (mix 1.10.4) lib/mix/tasks/compile.all.ex:27: anonymous fn/2 in Mix.Tasks.Compile.All.run/1
    (mix 1.10.4) lib/mix/tasks/compile.all.ex:43: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.10.4) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.4) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
```

Not looking for support just dropping the error message here as a data point. :P

**Comment by toranb** [comment]
hey dude! What version of gleam do you have installed locally w/ brew?

```
┌──(~/Desktop)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(✔)─
└──➤ gleam --version
gleam 0.11.2
```

edit: I usually do this from a fresh clone running elixir 1.10.3 and OTP 22.X

```
git clone git@github.com:toranb/elixir-gleam-match.git
cd elixir-gleam-match
mix deps.get
npm i --prefix assets
mix compile
iex -S mix phx.server
```

**Comment by dustinfarris** [comment]
aha, I used

```
asdf install gleam latest
```

which installed 0.9.x for some reason

```
asdf install gleam 0.11.2
```

got me up and running.  👍 

Thanks!
